name: Lint and test

on:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - uses: 'lagren/setup-task@v1'

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
      - run: go vet

      - name: lint
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
          install-go: false

      - name: tests
        run: task test

